# Install (on Windows only install DLLs)
if (WIN32)
	install(TARGETS StormByte StormByte-System
		RUNTIME 		DESTINATION ${CMAKE_INSTALL_BINDIR}
	)
elseif (NOT STORMBYTE_AS_DEPENDENCY)
	install(TARGETS StormByte-System
		ARCHIVE 		DESTINATION "${CMAKE_INSTALL_LIBDIR}"
		LIBRARY 		DESTINATION "${CMAKE_INSTALL_LIBDIR}"
		RUNTIME 		DESTINATION ${CMAKE_INSTALL_BINDIR}
	)
	install(DIRECTORY "${CMAKE_SOURCE_DIR}/lib/public/StormByte/"
		DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/StormByte"
		FILES_MATCHING
		PATTERN "*.h"
		PATTERN "*.hxx"
	)
endif()