install(TARGETS StormByte-System
	ARCHIVE 		DESTINATION "${CMAKE_INSTALL_LIBDIR}"
	LIBRARY 		DESTINATION "${CMAKE_INSTALL_LIBDIR}"
	RUNTIME 		DESTINATION ${CMAKE_INSTALL_BINDIR}
)
install(DIRECTORY "${CMAKE_SOURCE_DIR}/lib/public/StormByte/"
	DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/StormByte"
	FILES_MATCHING
	PATTERN "*.h"
	PATTERN "*.hxx"
)