# Optimizations
if (CMAKE_BUILD_TYPE STREQUAL "Release" AND MSVC)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /O2 /GL /Gy /arch:AVX2 /fp:fast /DNDEBUG")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /O2 /GL /Gy /arch:AVX2 /fp:fast /DNDEBUG")
	set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /LTCG")
	set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /LTCG")
endif()