if (NOT STORMBYTE_AS_DEPENDENCY)
	message(STATUS "C Flags:         ${CMAKE_C_FLAGS}")
	message(STATUS "CXX Flags:       ${CMAKE_CXX_FLAGS}")
	message(STATUS "Exe Linker:      ${CMAKE_EXE_LINKER_FLAGS}")
	message(STATUS "Shared Linker:   ${CMAKE_SHARED_LINKER_FLAGS}")
endif()